services:
  php:
    image: farmos/farmos:2.0.0-beta6
    default: true
    commands:
      
      # Commands that set up the basic preview infrastructure.
      init: |
        set -eux

        # Additional composer dependencies.
        cd /opt/drupal
        composer require drupal/role_delegation drupal/userprotect drupal/farm_nrcs -W --no-install
        composer install --no-cache --no-interaction
      
      # Commands that import files, databases, or other assets.
      # When an existing preview is refreshed, the build workflow starts
      # here, skipping the build step.
      update: |
        # Do not print commands with their arguments because it contains sensitive information.
        set -eu

        # Create a files directory.
        mkdir -p /opt/drupal/web/sites/default/files
        
        # Drush site-install to a sqlite file.
        drush site:install --db-url=sqlite://sites/default/files/db.sqlite --account-name=admin --account-pass=$ADMIN_PASSWORD farm farm.modules='all' --yes
        
        # Additional farmOS modules.
        drush en farm_nrcs farm_quick_planting --yes

        # Configure mapbox.
        drush en farm_map_mapbox --yes
        drush config:set farm_map_mapbox.settings api_key $MAPBOX_API_KEY --yes

        # Configure demo admin role.
        drush en role_delegation
        drush en userprotect
        drush config:import --partial --source $TUGBOAT_ROOT/drupal/config -y

        # Update ownership of files so www-data has access to db.
        chgrp -R www-data /opt/drupal/web/sites/default/files
        chmod 2775 /opt/drupal/web/sites/default/files
        chmod -R g+w /opt/drupal/web/sites/default/files

        # Update ownership of keys directory.
        chown -R www-data:www-data /opt/drupal/keys

        # Download and import farmOS translations.
        # TODO: Add --autocreate-language flag for drush 11.
        for locale in de es it nl
        do
          curl "https://ftp.drupal.org/files/translations/all/farm/farm-2.0.0-beta2.$locale.po" -o "/opt/drupal/web/sites/default/files/translations/farm-$locale.po" --silent
          drush locale:import $locale /opt/drupal/web/sites/default/files/translations/farm-$locale.po
        done

        # Update all module translations.
        drush locale:update
      
      # Commands that build the site. When a preview is built from a base
      # preview, the build workflow starts here, skipping the init and 
      # update steps.
      build: |
        # Generate build_steps.json using
        # tugboat validate .tugboat/config.yml | jq "map_values(del(.php.commands.init, .php.commands.update))" > .tugboat/build_steps.json
        set -ex

        # Set the site name equal to the preview name.
        drush config:set system.site name "$TUGBOAT_PREVIEW_NAME" --yes

        # Only create users once building the final preview.
        if [ $TUGBOAT_BASE_PREVIEW ]; then

          # Create test users with manager, worker and viewer roles.
          drush user-create manager --password manager && drush user-add-role farm_manager manager && drush user-add-role demo_admin manager
          drush user-create worker && drush user-add-role farm_worker worker
          drush user-create viewer && drush user-add-role farm_viewer viewer

          # Create a login link for the manager user.
          drush uli --uri $TUGBOAT_SERVICE_URL --name manager dashboard
        fi

        # TODO: Find a better approach for this.
        # This is temporary so users can be created with the specified language.
        # Ensure the site ends up with english as the default language.
        drush config:set system.site default_langcode en --yes

        # Clear the cache.
        drush cache:rebuild
