services:
  php:
    image: farmos/farmos:2.x
    default: true
    commands:
      
      # Commands that set up the basic preview infrastructure.
      init: |
        set -eux
      
      # Commands that import files, databases, or other assets.
      # When an existing preview is refreshed, the build workflow starts
      # here, skipping the build step.
      update: |
        set -eux

        # Create a files directory.
        mkdir -p /opt/drupal/web/sites/default/files
        
        # Drush site-install to a sqlite file.
        drush site:install --yes --db-url=sqlite://sites/default/files/db.sqlite --account-name=admin farm farm.modules='all'

        # Configure mapbox.
        drush en farm_map_mapbox --yes
        drush config:set farm_map_mapbox.settings api_key $MAPBOX_API_KEY --yes

        # Create test users with manager, worker and viewer roles.
        drush user-create manager && drush user-add-role farm_manager manager
        drush user-create worker && drush user-add-role farm_worker worker
        drush user-create viewer && drush user-add-role farm_viewer viewer

        # Update ownership of files so www-data has access to db.
        chgrp -R www-data /opt/drupal/web/sites/default/files
        chmod 2775 /opt/drupal/web/sites/default/files
        chmod -R g+w /opt/drupal/web/sites/default/files

        # Update ownership of keys directory.
        chown -R www-data:www-data /opt/drupal/keys
      
      # Commands that build the site. When a preview is built from a base
      # preview, the build workflow starts here, skipping the init and 
      # update steps.
      build: |
        set -eux

        # Set the site name equal to the preview name.
        drush config-set system.site name "$TUGBOAT_PREVIEW_NAME" --yes

        # Create a login link for the manager user.
        drush uli --uri $TUGBOAT_SERVICE_URL --name manager dashboard

        # Clear the cache.
        drush cache:rebuild